# Generated by Django 4.2 on 2023-04-12 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите категорию товаров', max_length=200, verbose_name='Категория товаров')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта', max_length=200, verbose_name='Название продукта')),
                ('serial_number', models.CharField(help_text='Введите серийный номер', max_length=4, verbose_name='Серийный номер')),
                ('vp', models.DecimalField(decimal_places=2, help_text='Введите VP', max_digits=5, null=True, verbose_name='VP продукта')),
                ('proc100', models.DecimalField(decimal_places=2, help_text='100', max_digits=8, null=True, verbose_name='100')),
                ('proc50', models.DecimalField(decimal_places=2, help_text='50', max_digits=8, null=True, verbose_name='50')),
                ('proc42', models.DecimalField(decimal_places=2, help_text='42', max_digits=8, null=True, verbose_name='42')),
                ('proc35', models.DecimalField(decimal_places=2, help_text='35', max_digits=8, null=True, verbose_name='35')),
                ('proc25', models.DecimalField(decimal_places=2, help_text='25', max_digits=8, null=True, verbose_name='25')),
                ('proc15', models.DecimalField(decimal_places=2, help_text='15', max_digits=8, null=True, verbose_name='15')),
                ('category', models.ForeignKey(help_text='Введите категорию товара', null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.category', verbose_name='Категория товара')),
            ],
        ),
    ]
